### ISSUE TITLE
'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by Silver292** [Akuukis/beancount_share#1]
Hi,

Thanks for the great plugin. It finally made me switch to beancount. 

I am having an error when running the plugin however,

### Error:
``` python
$ bean-report sharedemo.beancount balances
Traceback (most recent call last):
  File "/usr/local/bin/bean-report", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/beancount/reports/report.py", line 243, in main
    entries, errors, options_map = loader.load_file(args.filename,
  File "/usr/local/lib/python3.8/dist-packages/beancount/loader.py", line 89, in load_file
    entries, errors, options_map = _load_file(
  File "/usr/local/lib/python3.8/dist-packages/beancount/loader.py", line 214, in wrapped
    result = function(toplevel_filename, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/beancount/loader.py", line 255, in _uncached_load_file
    return _load([(filename, True)], *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/beancount/loader.py", line 510, in _load
    entries, errors = run_transformations(entries, parse_errors, options_map,
  File "/usr/local/lib/python3.8/dist-packages/beancount/loader.py", line 585, in run_transformations
    entries, plugin_errors = callback(entries, options_map,
  File "/usr/local/lib/python3.8/dist-packages/beancount_share/share.py", line 61, in share
    marked_postings_result = list(marked_postings(tx, config.mark_name, ("Income", "Expenses")))
  File "/usr/local/lib/python3.8/dist-packages/beancount_share/common.py", line 74, in marked_postings
    marks = metaset.get(_posting.meta, mark_name)
  File "/usr/local/lib/python3.8/dist-packages/beancount_share/metaset.py", line 52, in get
    return [v for k,v in meta.items() if contains_key(key, k)]
AttributeError: 'NoneType' object has no attribute 'items'
```

I have attached a minimal reproduction of the issue in the [txt file](https://github.com/Akuukis/beancount_share/files/5692034/sharedemo.txt), the contents are below.

### Reproduction:
```
plugin "beancount_share.share" "{}"

2020-01-01 open Equity:Opening-Balances CHF

2020-01-01 open Assets:Bank CHF
2020-01-01 open Assets:Savings CHF

2020-01-01 pad Assets:Bank Equity:Opening-Balances

2020-02-02 balance Assets:Bank 2000 CHF

2020-11-17 * "Savings"
  Assets:Savings         1000 CHF
  Assets:Bank           -1000 CHF
```

I have tracked it down to this line that passes `None` for the meta parameter.https://github.com/Akuukis/beancount_share/blob/cf8ab1ec560ad1125aad0709f91abed30b8ca84c/beancount_share/common.py#L88

I am currently wrapping this part of the code in a check but I don't know the code well enough to know if this is correct.

```python
        if _posting.meta is not None:
            marks = metaset.get(_posting.meta, mark_name)
            posting = _posting._replace(meta=metaset.clear(_posting.meta, mark_name))

            if len(marks) > 0:
                yield marks, posting, _posting, copy
            elif len(default_marks) > 0:
                if posting.account.split(":")[0] not in applicable_account_types:
                    yield None, posting, _posting, copy
                else:
                    yield default_marks, posting, _posting, copy
        else:
            print('posting meta was none')
            yield None, _posting, _posting, copy
```
Cheers!

**Comment by Akuukis** [comment]
@Silver292 thank you for such a detailed bug report! It allowed me to fix the problem, add your repro as a test, and publish a new version, all in 10 minutes only :rocket: Please update the plugin to 0.1.3.

 I'm glad to hear it helps you, happy beancounting!
